### ISSUE TITLE
The library cannot be built

### ISSUE THREAD

**Issue by pbfordev** [iwbnwif/wxFreeChart#23]
There are currently two issues preventing wxFreeChart from being built (using wxFreeChart_vc9.sln):
1. In [NumberAxis::SetLabelCount() declaration](https://github.com/iwbnwif/wxFreeChart/blob/master/include/wx/axis/numberaxis.h#L37) after the wxDEPRECATED_MSG macro is a semicolon that does not belong there. 
2. In [NumberAxis::UpdateBounds()](https://github.com/iwbnwif/wxFreeChart/blob/master/src/axis/numberaxis.cpp#L137) DEFAULT_MAJOR_LABEL_COUNT is referenced which is not declared anywhere.

**Comment by iwbnwif** [comment]
Thanks for the report.

> In NumberAxis::SetLabelCount() declaration after the wxDEPRECATED_MSG macro is a semicolon that does not belong there.

I can't see the extra semicolon - is it there in a05ce58?

> In NumberAxis::UpdateBounds() DEFAULT_MAJOR_LABEL_COUNT is referenced which is not declared anywhere.

Sorry, I didn't include a new version of wxfreechartdefs.h in the commit. It should be there in dc9c77a.

I should mention that I am making a lot of various tests and updates at the moment. I probably should have created a new branch - but didn't bother because there is almost noone using it!

**Comment by pbfordev** [comment]
Regarding the semicolon, it is not there! But I swear it was there when I downloaded the source tree as a zip and also when I forked and cloned the repository.

Anyway, I am afraid I cannot be of much help with coding but I could provide some suggestions regarding your changes. Not sure if you would want to hear them though. :)

BTW, bugs aside, the two features I was missing the most were: (1) interactivity (i.e. getting events from the user actions over the chart), (2) zoom & pan.

**Comment by pbfordev** [comment]
Regarding the semicolon, sorry it was in different file(s), see #25.

**Comment by iwbnwif** [comment]
Thanks for the PR. Hopefully the library should build okay now, please let me know if there are further problems.

**Comment by iwbnwif** [comment]
> Anyway, I am afraid I cannot be of much help with coding but I could provide some suggestions regarding your changes. Not sure if you would want to hear them though. :)
Of course, this is a bit of a learning exercise for me, so getting other opinions is part of that.

> BTW, bugs aside, the two features I was missing the most were: (1) interactivity (i.e. getting events from the user actions over the chart), (2) zoom & pan.
Events is definitely on my list, I need it to show tooltips about the data points.
Zoom and pan isn't something that I really thought about, but I wanted to look at fast zooming and panning on another library (wxShapeFramework) so maybe there is some copy across.
