### ISSUE TITLE
Pieplot and Multiplot fixes

### ISSUE THREAD

**Issue by Valnamu** [iwbnwif/wxFreeChart#29]
Hello !
I wanted to try wxFreeChart, so cloned your repo and compiled the library and samples.
I had to fix compatibility issues for wx 2.8 and 3.0
Testing the sample demo showed that Pie and CombinedAxis demos did not display anything on my screen.
I had to fix pieplot and multiplot to get them working.
Are you interested in my (small) patches ?
I am very new to github and don't know how to send you my local commits...
Thanks

**Comment by iwbnwif** [comment]
Hi,
> Are you interested in my (small) patches ?
Yes please, but I may not be able to apply them as it depends which build you are using (I am currently working on a different branch).

Which platform and compiler do you have, because I thought I had solved the problems with MultiPlot and I don't have any trouble with PiePlot?

> I am very new to github and don't know how to send you my local commits...

I don't know much about Github (or Git) either. I think one way is to create your own Github account, upload your changed source and then create a pull request.

If the changes are very small, probably the best thing is to create a patch with `git diff filename.cpp > pieplotfix.diff` etc. and add it here.

**Comment by Valnamu** [comment]
Hi !
- my toolchain is MinGW 32 bits, with gcc 4.4.3
- I use wxWidgets 2.8.12 and 3.0.2 --> I had to add some #defines depending upon which wx version is used. 
- after that, wxFreeChart lib compiles and links ok, without errors.
- I next compiled the sample/demos. Compiles/links without errors.
- when running demo, all demos display ok, except:
     Combined Axis 1 & 2
     Pieplot
for these 3 demos, the graphic panel only displays title, no graphics nor background are drawn:

![multaxis_is_ok](https://cloud.githubusercontent.com/assets/27493730/25566386/dc930a6a-2dd7-11e7-9783-51e0cdbfbeaf.png)

![pie_bug](https://cloud.githubusercontent.com/assets/27493730/25566383/ccf22654-2dd7-11e7-88d2-e5182ea46b11.png)
after my fixes:
![pie_after_fix](https://cloud.githubusercontent.com/assets/27493730/25566387/e4e82222-2dd7-11e7-9f7b-90025d9e65d9.png)

- after looking at code, I found that in pieplot and multiplot, Drawdata is never called.
- AFAIK other plots types draw background by calling DrawDataAreaBackground, which itself calls Drawdata...

You say you have no problem with multiplot & pieplot ... I can't understand how it can display anything as is... Maybe you explicitly call drawdata yourself ? Did you run the included sample/demo with success ?

I uploaded my changes here: https://github.com/Valnamu/wxFreeChart

thanks

**Comment by iwbnwif** [comment]
Hi, I think you must have at least some of your code from an old commit.

Looking at your Github repository, it only has commits up to the April 13, which indeed had some problems with drawing. I removed the DrawDataAreaBackground method a couple of weeks ago to try another way.

I suggest it might be best to grab the latest Master (I wouldn't bother with the V2_0_dev branch for now) and see if that fixes anything.

**Comment by Valnamu** [comment]
Thanks !
you were right.
After updating my local repo, I could succesfully compile and run the demo which act as expected.

However I had to do some patches to adapt the code to the version of wxWidgets I use: 2.8.12 and 3.0.2.
Finally, I had to fix a "friend" declaration because GCC compiler is very strict on the standard syntax and insists on having the full declaration "friend **class** myclass"...
Maybe you could insert my patches in your master, that would facilitate porting to other environments.
You can find them at my repo Valnamu/wxFreeChart, branch "wx30":
https://github.com/Valnamu/wxFreeChart/tree/wx30

Thanks for your work on bug fixes and improvements !

**Comment by iwbnwif** [comment]
> However I had to do some patches to adapt the code to the version of wxWidgets I use: 2.8.12 and 3.0.2.
Sorry but I am not sure about this, is it really necessary to support such an old version of wxWidgets?

> Finally, I had to fix a "friend" declaration because GCC compiler is very strict on the standard syntax and insists on having the full declaration "friend class myclass"...

Thanks, yes good fix. I have added this now.

Anyway, I think that the title issue is resolved so closing it.
