### ISSUE TITLE
Dynamic dataset works with wxTimer but not with wxThread.

### ISSUE THREAD

**Issue by psychegr** [iwbnwif/wxFreeChart#39]
I compiled and trying the new version. I have to say that the new way to create datasets and create a chart in overall is way easier than before. I think it is fewer code lines.
The issue that i am having is that i am trying to update/add datapoints to a dataset realtime. 
Using the wxTimer event it works, i have to say that i noticed some flickering.
But when i am trying to update/add datapoints using a wxThread event, it fails and only shows the data after the wxThread is stopped. I am not updating the values from inside the wxThread but from an event that is posted in the main thread. The update rate is about 10mS and the datapoints are about 1000. I noticed the same behaviour with the old 1.6 version so i think that either it is a fault in my code or in the wxFreeChart code. 

Here is how i am updating the dataset :
`m_dataset->GetSeries(0)->AddPoint(new BiDataPoint(time, value));`
`m_dataset->DatasetChanged();`

if i run this code in the timer event it works. The same code doesnt work on the thread event.

**Comment by iwbnwif** [comment]
Good to hear you like the new data set structure :) thanks!

There is a possible performance problem at the moment with anything other than a small number of data points. I haven't got to the bottom of it yet, but I think it is to do with wxAny access being *significantly* slower than direct pointer access.

That said, if it is working with a wxTimer, then I am not sure why a thread should be any different.

I have added a 'throttle' mechanism in wxChartPanel that should prevent redraws occurring more often than every 10mS. I wonder if this is clashing somehow? (it shouldn't)

The best thing is to see if wxChartPanel is receiving any OnChartChanged events and if not, try to work out why.

**Comment by psychegr** [comment]
Yes i like the new dataset structure, makes things easier for me at least! 
Regarding the issue/bug, call it what ever you want. 
One thing i have to say, your code works fine. I spent many hours trying to find where the issue is and it seems that this issue happens when i update another control that i am making. I am also updating the value of an angular meter which i am developing based on the KOAN industrial controls. When i remove the line that updates the meter, the chart updates fine. If i put the meter update line back in, the chart stops updating but the meter works fine. That is something that i need to figure out, maybe it is the wxGCDC or something else. Maybe i need to find where you put that "throttle" mechanism in wxChartPanel and do the same for the control that i am developing.

I will get back to you as soon as i find the solution and what causes this issue.

**Comment by psychegr** [comment]
Ok, after a few hours of debugging it turned out to be a mistake in my meter code. The thing is that i didnt use a bitmap to draw the meter, i was drawing directly with wxGCDC without wxMemoryDC or anything like that. I have changed the complete code in my meter to use wxMemoryDC and wxGCDC and now both freechart and the meter update. I am still working in my code as there is a small glitch, like a lag after a few seconds. Both my meter and freechart lag in updating. But if i update only one of the 2 it works fine. So maybe i need to use your "throttle" mechanism in the meter and see the results.

I consider this issue as resolved and closed as this is not a real problem of freechart.
