### ISSUE TITLE
Compile errors with current (3.1.2) wxWidgets

### ISSUE THREAD

**Issue by Lys0gen** [iwbnwif/wxFreeChart#46]
Errors appear in the following files/lines:
xydynamicdataset.cpp:99
WX_APPEND_ARRAY is apparently not recognized by the current wxWidgets.

dataset.cpp:149
DatasetArrayBase::Remove parameter is not valid anymore. Since I have no clue how those dynamic arrays and wxWidgets macros function I just replaced it with a loop that compares the parameter and then utilizes RemoveAt instead which still works.

Someone who knows how this all works probably has proper solutions for this.

The sample also no longer auto compiles due to renamed libraries/linker errors.

**Comment by QFer** [comment]
Fixed in pull request #47 for wxWidgets 3.1.3

**Comment by iwbnwif** [comment]
Thank you for the PR, this is merged now. I would really like to move away from these arrays and standardise on wxVectors.
